import { Team } from './Team.js';
import { buyStaffForTeam } from './buyStaffForTeam.js';

let teamNames = [
	'Abarth',
	'AC',
	'Acura',
	'AIXAM',
	'Alfa Romeo',
	'Alpine',
	'Arash',
	'Ariel',
	'Artega',
	'Ascari',
	'Aston Martin',
	'Audi',
	'AvtoVAZ',
	'BAIC',
	'Bentley',
	'BMW',
	'Borgward',
	'Brilliance',
	'Bristol',
	'Bufori',
	'Bugatti',
	'Buick',
	'Byton',
	'Cadillac',
	'Caterham',
	'Changan',
	'Changhe',
	'Chery',
	'Chevrolet',
	'Chrysler',
	'Citroen',
	'Coda',
	'CT&T',
	'Dacia',
	'Daewoo',
	'DAF',
	'Daihatsu',
	'Datsun',
	'Dodge',
	'Donkervoort',
	'DS',
	'Ferrari',
	'Fiat',
	'Fisker',
	'Force Motors',
	'Ford',
	'Foton',
	'GAZ',
	'Geely',
	'Genesis',
	'Ginetta',
	'GMC',
	'Great Wall',
	'Haima',
	'Hino',
	'Holden',
	'Honda',
	'Hyundai',
	'Iconic',
	'Infiniti',
	'Isuzu',
	'JAC',
	'Jaguar',
	'Jeep',
	'JMC',
	'Kia',
	'Koenigsegg',
	'Lamborghini',
	'Lancia',
	'Land Rover',
	'Landwind',
	'Lexus',
	'Lifan',
	'Lincoln',
	'Lotus',
	'Luxgen',
	'Magna Steyr',
	'Mahindra',
	'Maserati',
	'Maxus',
	'Maybach',
	'Mazda',
	'Mazzanti',
	'McLaren',
	'Mercedes-Benz',
	'MG',
	'Mini',
	'Mitsubishi',
	'Mitsuoka',
	'Morgan',
	'Morris',
	'NIO',
	'Nissan',
	'Noble',
	'Opel',
	'Pagani',
	'Perodua',
	'Peugeot',
	'Polestar',
	'Pontiac',
	'Porsche',
	'Proton',
	'Ram',
	'Reliant',
	'Renault',
	'Rimac',
	'Rivian',
	'Rolls-Royce',
	'RUF',
	'Saab',
	'Saleen',
	'Saturn',
	'Scion',
	'SEAT',
	'Senova',
	'SIN Cars',
	'Skoda',
	'Smart',
	'Spyker',
	'Ssangyong',
	'Subaru',
	'Suzuki',
	'Tata',
	'Tatra',
	'Tesla',
	'Toyota',
	'Trumpchi',
	'TVR',
	'Vauxhall',
	'Volkswagen',
	'Volvo',
	'W Motors',
	'Wiesmann',
	'Zenos',
	'Zenvo',
	'Acer',
	'Alta',
	'Arrows',
	'Asiatech',
	'ATS',
	'BPM',
	'BRM',
	'Butterworth',
	'BWT Mercedes',
	'Castellotti',
	'Climax',
	'Conrero',
	'Cosworth',
	'De Tomaso',
	'EMW',
	'ERA',
	'European',
	'Fondmetal',
	'Gordini',
	'Hart',
	'Ilmor',
	'JAP',
	'Judd',
	'Küchen',
	'Lea-Francis',
	'Life',
	'Matra',
	'Mecachrome',
	'Megatron',
	'Motori Moderni',
	'Mugen-Honda',
	'OSCA',
	'Osella',
	'Petronas',
	'Playlife',
	'Red Bull Powertrains[p]',
	'Repco',
	'Sauber',
	'Scarab',
	'Serenissima',
	'Supertec',
	'TAG',
	'TAG Heuer',
	'Talbot',
	'Tecno',
	'Toro Rosso',
	'Vanwall',
	'Veritas',
	'Weslake',
	'Yamaha',
	'Zakspeed'
];

function createSeasonTeams(driverArray, teamsToGenerate, staff, drivers, season) {
	let potentialTeams = [];
	let teamOwnerPool = [];
	
	for(let i=0; i<teamsToGenerate; i++) {
		//Temporary
		let name = teamNames[Math.floor(Math.random() * teamNames.length)] ? teamNames[Math.floor(Math.random() * teamNames.length)] : `Team ${i}-${season.name}`;
		let team = new Team(name);
		teamNames = teamNames.filter(item => item !== name);

		teamOwnerPool = staff.filter(member => { 
			let memberToReturn = {};
			if(!member.team && member.teamsOwned.length === 0) memberToReturn = member;
			return memberToReturn;
		});

		if(teamOwnerPool.length > 0) {
			teamOwnerPool.sort(function(a, b) {
				return b.funds - a.funds;
			});
			teamOwnerPool[0].teamsOwned.push(team);
			team.owner = teamOwnerPool[0];
			teamOwnerPool = teamOwnerPool.filter(owner => owner.name !== team.owner.name);
		}
	
		team = buyStaffForTeam(team, staff, drivers, season);
		if(team.drivers.length > 0) potentialTeams.push(team);
	}

	return potentialTeams;
}

export { createSeasonTeams };