const Chassis = {
	sname: 'Chassis',
	focus: [{
		name: 'Suspension',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}, {
		name: 'Steering',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}, {
		name: 'Structure',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}, {
		name: 'Tires',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}, {
		name: '1.5',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}]
};

export { Chassis };