const Finance = {
    name: 'Finance',
    focus: [{
        name: 'Taxation',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }, {
        name: 'Materials',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }, {
        name: 'Expendature',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }, {
        name: 'Marketing',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }, {
        name: 'Law',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }]
}

export { Finance };