const Logistics = {
    name: 'Logistics',
    focus: [{
        name: 'PR',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }, {
        name: 'Production',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }, {
        name: 'Staff',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }, {
        name: 'Travel',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }, {
        name: 'Data',
        technology: [{
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }, {
            name: 'ITEM',
            invention: [],
            unlocked: false
        }]
    }]
}

export { Logistics };