const Power = {
	name: 'Power',
	focus: [{
		name: 'ICE',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}, {
		name: 'Energy',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}, {
		name: 'Gearbox',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}, {
		name: 'Exhaust',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}, {
		name: 'Fuel',
		technology: [{
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}, {
			name: 'ITEM',
			invention: [],
			unlocked: false
		}]
	}]
};

export { Power };